version: "3.9"

services:
  frontend:
    image: tms:frontend
    ports:
      - "3003:3000"
    networks:
      - tms_net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
      labels:
        swarm.autoscaler: "true"
        swarm.autoscaler.minimum: "1"
        swarm.autoscaler.maximum: "5"

  backend:
    image: tms:backend
    command: gunicorn tms_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8888:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - ./tms_backend/.env
    networks:
      - tms_net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      labels:
        swarm.autoscaler: "true"
        swarm.autoscaler.minimum: "1"
        swarm.autoscaler.maximum: "5"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tms_database
      POSTGRES_USER: tms_user
      POSTGRES_PASSWORD: tms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tms_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tms_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

networks:
  tms_net:
    external: true

volumes:
  postgres_data:
