version: "3.8"

services:
  web:
    #docker build -t tms_backend:latest .
    #docker stack deploy -c docker-compose.yml tms_backend
    image: tselot24/tms_back:latest
    #build: .
    #container_name: tms_backend
    command: gunicorn tms_backend.wsgi:application --bind 0.0.0.0:8000
    #volumes:
     # - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - tms_net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      labels:
        swarm.autoscaler: "true" # Enable autoscaling
        swarm.autoscaler.minimum: "1" # Minimum replicas
        swarm.autoscaler.maximum: "5" # Maximum replicas

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tms_database
      POSTGRES_USER: tms_user
      POSTGRES_PASSWORD: tms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tms_net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "tms_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

networks:
  tms_net:
    external: true

volumes:
  postgres_data:
