# Generated by Django 5.1.6 on 2025-04-03 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_maintenancerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
