# Generated by Django 5.1.6 on 2025-04-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_maintenancerequest_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="maintenance_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.maintenancerequest",
            ),
        ),
    ]
