# Generated by Django 5.1.6 on 2025-04-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification_maintenance_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="transport_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.transportrequest",
            ),
        ),
    ]
