# Generated by Django 5.1.6 on 2025-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_notification_transport_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_request", "New Transport Request"),
                    ("forwarded", "Request Forwarded"),
                    ("approved", "Request Approved"),
                    ("rejected", "Request Rejected"),
                    ("assigned", "Vehicle Assigned"),
                ],
                max_length=100,
            ),
        ),
    ]
