# Generated by Django 5.1.6 on 2025-04-08 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="refueling_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.refuelingrequest",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="maintenance_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.maintenancerequest",
            ),
        ),
    ]
