# Generated by Django 5.1.6 on 2025-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification_refueling_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="current_approver_role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Department Manager"),
                    (3, "Finance Manager"),
                    (4, "Transport Manager"),
                    (5, "CEO"),
                    (6, "Driver"),
                    (7, "System Admin"),
                    (8, "General System Excuter"),
                    (9, "Budget Manager"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="refuelingrequest",
            name="current_approver_role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Department Manager"),
                    (3, "Finance Manager"),
                    (4, "Transport Manager"),
                    (5, "CEO"),
                    (6, "Driver"),
                    (7, "System Admin"),
                    (8, "General System Excuter"),
                    (9, "Budget Manager"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="transportrequest",
            name="current_approver_role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Department Manager"),
                    (3, "Finance Manager"),
                    (4, "Transport Manager"),
                    (5, "CEO"),
                    (6, "Driver"),
                    (7, "System Admin"),
                    (8, "General System Excuter"),
                    (9, "Budget Manager"),
                ],
                default=2,
            ),
        ),
    ]
