# Generated by Django 5.1.6 on 2025-04-12 08:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_maintenancerequest_current_approver_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refuelingrequest",
            name="estimated_distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refuelingrequest",
            name="fuel_needed_liters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="refuelingrequest",
            name="fuel_price_per_liter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="refuelingrequest",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_efficiency",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Distance the vehicle can travel per liter of fuel (km/L).",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
            preserve_default=False,
        ),
    ]
