# Generated by Django 5.1.6 on 2025-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_refuelingrequest_estimated_distance_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[("naphtha", "Naphtha"), ("benzene", "Benzene")],
                default="benzene",
                max_length=10,
            ),
        ),
    ]
