# Generated by Django 5.1.6 on 2025-04-15 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_vehicle_fuel_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HighCostTransportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_day", models.DateField()),
                ("return_day", models.DateField()),
                ("start_time", models.TimeField()),
                ("destination", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("forwarded", "Forwarded"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_approver_role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Employee"),
                            (2, "Department Manager"),
                            (3, "Finance Manager"),
                            (4, "Transport Manager"),
                            (5, "CEO"),
                            (6, "Driver"),
                            (7, "System Admin"),
                            (8, "General System Excuter"),
                            (9, "Budget Manager"),
                        ],
                        default=2,
                    ),
                ),
                ("rejection_message", models.TextField(blank=True, null=True)),
                (
                    "estimated_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fuel_price_per_liter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fuel_needed_liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employees",
                    models.ManyToManyField(
                        related_name="highcost_travel_group",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highcost_transport_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="highcost_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.highcosttransportrequest",
            ),
        ),
    ]
