# Generated by Django 5.1.6 on 2025-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_highcosttransportrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refuelingrequest",
            name="destination",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="refuelingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("forwarded", "Forwarded"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
