# Generated by Django 5.1.6 on 2025-04-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_highcosttransportrequest_current_approver_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highcosttransportrequest",
            name="estimated_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimated_highcost_requests",
                to="core.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="highcosttransportrequest",
            name="vehicle_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
