# Generated by Django 5.1.6 on 2025-04-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_highcosttransportrequest_estimated_vehicle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highcosttransportrequest",
            name="trip_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transportrequest",
            name="trip_completed",
            field=models.BooleanField(default=False),
        ),
    ]
