# Generated by Django 5.1.6 on 2025-04-26 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_maintenancerequest_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_service_kilometers",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="total_kilometers",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="MonthlyKilometerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("kilometers_driven", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vehicle"
                    ),
                ),
            ],
            options={
                "unique_together": {("vehicle", "month")},
            },
        ),
    ]
