# Generated by Django 5.1.6 on 2025-04-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_vehicle_last_service_kilometers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.vehicle",
            ),
        ),
    ]
